---
preset: conventionalcommits
branches:
  - main
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/github"
  - - "@semantic-release/changelog"
    - changelogTitle: '# Changelog'
  - - "@semantic-release/git"
    - assets:
      - CHANGELOG.md
  - semantic-release-major-tag
