---
- name: Provision common tooling
  hosts: all
  roles:
    - role: bruzit.ansible.apt
    - role: bruzit.ansible.users
      users_accounts: "{{ accounts }}"
    - role: bruzit.ansible.git
      git_users: "{{ accounts }}"
    - role: bruzit.ansible.claude
    - role: bruzit.ansible.direnv
    - role: bruzit.ansible.starship
    - role: bruzit.ansible.gh
      gh_users: "{{ accounts }}"
    - role: bruzit.ansible.terraform
    - role: bruzit.ansible.docker
      docker_users: "{{ accounts | map(attribute='name') }}"
    - role: bruzit.ansible.jq
    - role: bruzit.ansible.pwgen
    - role: bruzit.ansible.yq

- name: Provision desktop applications
  hosts: workstations
  roles:
    - role: bruzit.ansible.snap
    - role: bruzit.ansible.obsidian
    - role: bruzit.ansible.widelands
