---
accounts:
  - name: mb
    full_name: Martin Bružina
    email: martin@bruzina.cz
    repositories:
      - bruzit/.github
      - bruzit/ansible-collection
      - bruzit/github-actions-and-workflows
      - bruzit/github-organization-as-code
      - bruzit/infra
