---
accounts:
  - name: mb
    full_name: Martin Bružina
    email: martin@bruzina.cz
    signing_key: ~/.ssh/id_ed25519_signing
    github: bruzina
    admin: true
    repositories:
      - bruzit/.github
      - bruzit/ansible-collection
      - bruzit/github-actions-and-workflows
      - bruzit/github-organization-as-code
      - bruzit/infra
      - bruzit/template
